# This is a basic workflow to help you get started with Actions

name: Github CI

# Controls when the workflow will run
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v2
        with:
          start: npm start
          wait-on: "http://localhost:5000"
          browser: chrome
          headless: true
