name: Cypress tests
on: [push]
jobs:
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.SECRET_KEY }}
      - name: Cypress run
        run: npx cypress run --spec cypress/integration/Demoblaze/*spec.js --record --key ${{secret.SECRET_KEY}}
