name: Cypress tests
on: [push]
jobs:
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-20.04
    environment: dashboard-secret
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download the build folders
        uses: actions/download-artifact@v2
        with:
          name: build
          path: build
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          # we have already installed all dependencies above
          install: false
          start: npm ci
          wait-on-timeout: 120
          browser: chrome
          record: true
          parallel: true
          spec: cypress/integration/Demoblaze/*.spec.js
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.SECRET_KEY }}
